Added
moltin/js-sdk pull request #346
Opened 2020-09-17 16:40 UTC by rostyk-kanafotskyy

## Type

* ### Feature
  Implements the ability to assign customer id to cart

## Notes

*Any additional notes.*

2020-09-20 19:26 UTC, shaunmaharaj approved these changes

2020-09-21 06:39 UTC, dusanradovanovic approved these changes

2020-09-21 06:45 UTC, dusanradovanovic requested changes
Let's open this same PR against `beta` branch first so that it is first published as beta. Also make sure to edit message in one commit and use semantic-release format. You can undo one commit and then run `npx git-cz` which will guide you through the process.

2020-09-28 07:44 UTC, rostyk-kanafotskyy commented
> Let's open this same PR against `beta` branch first so that it is first published as beta. Also make sure to edit message in one commit and use semantic-release format. You can undo one commit and then run `npx git-cz` which will guide you through the process.

Done 
Squashed 2 commits into one with the right formatting 
Rebased against the beta branch

2020-09-29 15:48 UTC, shaunmaharaj approved these changes

2020-09-29 16:16 UTC, merged