[MT-6768] Filtering on /v2/account-members
moltin/js-sdk pull request #529
Opened 2021-08-31 06:57 UTC by razkevich

## Type

* ### Feature
  Implements a new feature
* ### Fix
  Fixes a bug
* ### Docs
  Documentation only changes
* ### Style
  Changes that **do not** affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* ### Refactor
  A code change that neither fixes a bug nor adds a feature
* ### Performance
  A code change that improves performance
* ### Test
  Adding missing or correcting existing tests
* ### Chore
  Changes to the build process or auxiliary tools and libraries such as documentation generation  

## Description

*A brief description of the goals of the pull request.*

## Dependencies

*Other PRs or builds that this PR depends on.*

## Issues

*A list of issues closed by this PR.*

* Fixes #

## Notes

*Any additional notes.*

2021-09-01 21:42 UTC, dr-ep requested changes

2021-09-01 21:42 UTC, dr-ep commented on playground/index.ts
> +    client_id: 'ueNTGjzwlYV2LkFbNwsPTWYau5nYEVBCcGIkHDrV9A',
Do not commit this file

2021-09-01 21:42 UTC, dr-ep commented on src/types/account-members.d.ts
> +import {FlowFilter} from "./flow";
Use single quotes

2021-09-02 04:27 UTC, razkevich commented on playground/index.ts
> +    client_id: 'ueNTGjzwlYV2LkFbNwsPTWYau5nYEVBCcGIkHDrV9A',
reverted, thanks.

2021-09-02 08:59 UTC, dr-ep approved these changes

2021-09-03 05:47 UTC, merged

2021-09-06 11:52 UTC, samblacklock commented
:tada: This PR is included in version 9.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@moltin/sdk/v/9.6.0)
- [GitHub release](https://github.com/moltin/js-sdk/releases/tag/v9.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: